apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-management-report-cronjob
spec:
  schedule: "30 20 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vidatec-daily-management-report
            image: vidatec_nfe_notify_import
            command: ["python", "dailyManagementReport.py"]
            resources:
              limits:
                cpu: "200m"
                memory: "384Mi"
              requests:
                cpu: "100m"
                memory: "128Mi"
            env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_HOST
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_PASS
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: SENDGRID_API_KEY
            - name: SENDGRID_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: SENDGRID_FROM_EMAIL
          restartPolicy: OnFailure