apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfe-nofity
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: main-container
        resources:
          limits:
            cpu: "200m" 
            memory: "384Mi" 
          requests:
            cpu: "100m" 
            memory: "128Mi"