apiVersion: batch/v1
kind: CronJob
metadata:
  name: nfe-nofity-cronjob
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vidatec-sandbox-nfe-nofity
            image: vidatec_nfe_notify_import
            command: ["python", "import-nfe.py"]
            resources:
              limits:
                cpu: "200m"
                memory: "384Mi"
              requests:
                cpu: "100m"
                memory: "128Mi"
            env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_HOST
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MYSQL_PASS
            - name: MSSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MSSQL_HOST
            - name: MSSQL_DB
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MSSQL_DB
            - name: MSSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MSSQL_USER
            - name: MSSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: nfe-nofity-secret
                  key: MSSQL_PASS
          restartPolicy: OnFailure