apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myevents-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myevents.sandbox.altmeyer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myevents
            port:
              number: 8080